//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const modulePath = "github.com/allbot/allbot/core/adapter"

func main() {
	adapterRoot := filepath.Clean(filepath.Join(".."))
	entries, err := os.ReadDir(adapterRoot)
	if err != nil {
		fatal("读取适配器目录失败: %v", err)
	}
	imports := make([]string, 0)
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, "_") || strings.HasPrefix(name, ".") {
			continue
		}
		manifestPath := filepath.Join(adapterRoot, name, "manifest.go")
		if _, err := os.Stat(manifestPath); err != nil {
			continue
		}
		imports = append(imports, modulePath+"/"+name)
	}
	sort.Strings(imports)
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by go generate ./core/adapter/_loader; DO NOT EDIT.\n")
	buffer.WriteString("package loader\n\n")
	if len(imports) > 0 {
		buffer.WriteString("import (\n")
		for _, item := range imports {
			buffer.WriteString("\t_ \"")
			buffer.WriteString(item)
			buffer.WriteString("\"\n")
		}
		buffer.WriteString(")\n")
	}
	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		fatal("格式化 loader 失败: %v\n%s", err, buffer.String())
	}
	outputPath := filepath.Join(adapterRoot, "_loader", "loader_gen.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fatal("写入 loader 失败: %v", err)
	}
}

func fatal(format string, args ...interface{}) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
