// Code generated by go generate ./core/adapter/_loader; DO NOT EDIT.
package loader

import (
	_ "github.com/allbot/allbot/core/adapter/dingtalk"
	_ "github.com/allbot/allbot/core/adapter/feishu"
	_ "github.com/allbot/allbot/core/adapter/qq"
	_ "github.com/allbot/allbot/core/adapter/qq_office"
	_ "github.com/allbot/allbot/core/adapter/telegram"
	_ "github.com/allbot/allbot/core/adapter/web"
	_ "github.com/allbot/allbot/core/adapter/wechat_official"
)
